import Foundation
import LibreChatDomain
import LibreChatProtocol
import Observation

enum FileLibrarySort: String, CaseIterable, Identifiable, Sendable {
    case updated
    case name
    case size

    var id: Self { self }

    var title: String {
        switch self {
        case .updated: "Recently updated"
        case .name: "Name"
        case .size: "Size"
        }
    }
}

struct FileLibraryPresentation {
    static func canDelete(_ item: FileLibraryItem) -> Bool {
        (try? LibreChatFilesAPI.delete(item)) != nil
    }

    static func visibleItems(
        in snapshot: FileLibrarySnapshot?,
        query: String,
        sort: FileLibrarySort
    ) -> [FileLibraryItem] {
        let normalized = query.trimmingCharacters(in: .whitespacesAndNewlines)
        let filtered = (snapshot?.items ?? []).filter { item in
            guard !normalized.isEmpty else { return true }
            return item.file.filename.localizedCaseInsensitiveContains(normalized)
                || item.file.mimeType?.localizedCaseInsensitiveContains(normalized) == true
                || kindLabel(for: item).localizedCaseInsensitiveContains(normalized)
        }

        return filtered.sorted { lhs, rhs in
            switch sort {
            case .updated:
                let leftDate = lhs.updatedAt ?? lhs.createdAt
                let rightDate = rhs.updatedAt ?? rhs.createdAt
                if leftDate != rightDate {
                    switch (leftDate, rightDate) {
                    case let (.some(left), .some(right)): return left > right
                    case (.some, .none): return true
                    case (.none, .some): return false
                    case (.none, .none): break
                    }
                }
            case .name:
                let order = lhs.file.filename.localizedStandardCompare(rhs.file.filename)
                if order != .orderedSame { return order == .orderedAscending }
            case .size:
                let leftSize = validBytes(lhs.file.bytes)
                let rightSize = validBytes(rhs.file.bytes)
                if leftSize != rightSize {
                    switch (leftSize, rightSize) {
                    case let (.some(left), .some(right)): return left > right
                    case (.some, .none): return true
                    case (.none, .some): return false
                    case (.none, .none): break
                    }
                }
            }

            let filenameOrder = lhs.file.filename.localizedStandardCompare(rhs.file.filename)
            if filenameOrder != .orderedSame { return filenameOrder == .orderedAscending }
            return lhs.id < rhs.id
        }
    }

    static func validBytes(_ bytes: Int64?) -> Int64? {
        guard let bytes, bytes >= 0 else { return nil }
        return bytes
    }

    static func kindLabel(for item: FileLibraryItem) -> String {
        guard let mime = item.file.mimeType?.lowercased() else { return "File" }
        if mime == "application/pdf" { return "PDF document" }
        if mime.hasPrefix("image/") { return "Image" }
        if mime.hasPrefix("audio/") { return "Audio" }
        if mime.hasPrefix("video/") { return "Video" }
        if mime.hasPrefix("text/") { return "Text document" }
        if mime.contains("spreadsheet") || mime.contains("excel") { return "Spreadsheet" }
        if mime.contains("presentation") || mime.contains("powerpoint") { return "Presentation" }
        if mime.contains("wordprocessing") || mime.contains("msword") { return "Document" }
        if mime.contains("zip") || mime.contains("archive") || mime.contains("compressed") {
            return "Archive"
        }
        return "File"
    }

    static func sourceLabel(for item: FileLibraryItem) -> String {
        switch item.file.source?.lowercased() {
        case "local", "firebase": "LibreChat storage"
        case "s3", "cloudfront", "azure_blob": "Cloud storage"
        case "openai", "azure": "Model provider storage"
        case "execute_code": "Generated by code"
        case "vectordb": "Vector store"
        case "mistral_ocr", "azure_mistral_ocr", "vertexai_mistral_ocr", "document_parser", "text":
            "Document processing"
        default: "Server-managed storage"
        }
    }

    static func contextLabel(for item: FileLibraryItem) -> String {
        switch item.file.context?.lowercased() {
        case "message_attachment": "Chat attachment"
        case "agents": "Agent resource"
        case "assistants": "Assistant resource"
        case "execute_code", "assistants_output": "Generated output"
        case "image_generation": "Generated image"
        case "avatar": "Profile image"
        case "skill_file": "Skill resource"
        default: "Account file"
        }
    }

    static func lifecycleLabel(for item: FileLibraryItem) -> String? {
        switch item.file.previewStatus?.lowercased() {
        case "pending": "Preview processing"
        case "ready": "Ready"
        case "failed": "Preview unavailable"
        default: nil
        }
    }
}

@MainActor
@Observable
final class FileLibraryModel {
    enum State: Equatable {
        case idle
        case loading
        case loaded
        case offline
        case forbidden
        case unavailable
        case unauthorized
        case failed(String)
    }

    private let repository: any FileLibraryRepository
    private let isOffline: @MainActor () -> Bool
    private let onUnauthorized: @MainActor () async -> Void
    private var revision: UInt64 = 0

    private(set) var state: State = .idle
    private(set) var snapshot: FileLibrarySnapshot?
    private(set) var refreshError: String?
    var query = ""
    var sort: FileLibrarySort = .updated

    init(
        repository: any FileLibraryRepository,
        isOffline: @escaping @MainActor () -> Bool,
        onUnauthorized: @escaping @MainActor () async -> Void
    ) {
        self.repository = repository
        self.isOffline = isOffline
        self.onUnauthorized = onUnauthorized
    }

    var visibleItems: [FileLibraryItem] {
        FileLibraryPresentation.visibleItems(in: snapshot, query: query, sort: sort)
    }

    var normalizedQuery: String {
        query.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    func loadIfNeeded() async {
        guard state == .idle else { return }
        await reload()
    }

    func reload() async {
        revision &+= 1
        let expectedRevision = revision
        guard !isOffline() else {
            if snapshot == nil {
                state = .offline
            } else {
                state = .loaded
                refreshError = "Reconnect to refresh this live file list."
            }
            return
        }

        if snapshot == nil { state = .loading }
        refreshError = nil
        do {
            let refreshed = try await repository.fileLibrary()
            guard expectedRevision == revision else { return }
            snapshot = refreshed
            state = .loaded
        } catch is CancellationError {
            return
        } catch {
            guard expectedRevision == revision else { return }
            await handle(error)
        }
    }

    func installReconciledSnapshot(_ snapshot: FileLibrarySnapshot) {
        revision &+= 1
        self.snapshot = snapshot
        refreshError = nil
        state = .loaded
    }

    private func handle(_ error: Error) async {
        if error.isUnauthorized {
            snapshot = nil
            state = .unauthorized
            await onUnauthorized()
            return
        }
        if case LibreChatProtocolError.httpStatus(403, _, _) = error {
            snapshot = nil
            state = .forbidden
            return
        }
        if case LibreChatProtocolError.httpStatus(let status, _, _) = error,
           status == 404 || status == 405 {
            snapshot = nil
            state = .unavailable
            return
        }
        if snapshot != nil {
            state = .loaded
            refreshError = error.userFacingMessage
        } else {
            state = .failed(error.userFacingMessage)
        }
    }
}

@MainActor
@Observable
final class FilePreviewModel {
    enum State: Equatable {
        case idle
        case loading
        case offline
        case processing
        case ready(FilePreviewSnapshot)
        case unavailable
        case forbidden
        case unsupported
        case unauthorized
        case failed(String)
    }

    private let repository: any FileLibraryRepository
    private let isOffline: @MainActor () -> Bool
    private let onUnauthorized: @MainActor () async -> Void
    private var revision: UInt64 = 0

    private(set) var state: State = .idle

    init(
        repository: any FileLibraryRepository,
        isOffline: @escaping @MainActor () -> Bool,
        onUnauthorized: @escaping @MainActor () async -> Void
    ) {
        self.repository = repository
        self.isOffline = isOffline
        self.onUnauthorized = onUnauthorized
    }

    func loadIfNeeded(fileID: String) async {
        guard state == .idle else { return }
        await reload(fileID: fileID)
    }

    func reload(fileID: String) async {
        revision &+= 1
        let expectedRevision = revision
        guard !isOffline() else {
            state = .offline
            return
        }

        state = .loading
        do {
            let preview = try await repository.filePreview(fileID: fileID)
            guard expectedRevision == revision else { return }
            guard preview.fileID == fileID else {
                state = .failed("LibreChat returned a preview for a different file.")
                return
            }
            switch preview.lifecycle {
            case .processing:
                state = .processing
            case .ready:
                state = .ready(preview)
            case .unavailable:
                state = .unavailable
            }
        } catch is CancellationError {
            return
        } catch {
            guard expectedRevision == revision else { return }
            await handle(error)
        }
    }

    private func handle(_ error: Error) async {
        if error.isUnauthorized {
            state = .unauthorized
            await onUnauthorized()
            return
        }
        if case LibreChatProtocolError.httpStatus(403, _, _) = error {
            state = .forbidden
            return
        }
        if case LibreChatProtocolError.httpStatus(let status, _, _) = error,
           status == 404 {
            state = .unavailable
            return
        }
        if case LibreChatProtocolError.httpStatus(let status, _, _) = error,
           status == 405 || status == 501 {
            state = .unsupported
            return
        }
        state = .failed(error.userFacingMessage)
    }
}

@MainActor
@Observable
final class FileDownloadModel {
    enum State: Equatable {
        case idle
        case downloading
        case ready(DownloadedLibraryFile)
        case offline
        case forbidden
        case unavailable
        case unauthorized
        case failed(String)
    }

    private let repository: any FileLibraryRepository
    private let isOffline: @MainActor () -> Bool
    private let onUnauthorized: @MainActor () async -> Void
    private var revision: UInt64 = 0

    private(set) var state: State = .idle

    init(
        repository: any FileLibraryRepository,
        isOffline: @escaping @MainActor () -> Bool,
        onUnauthorized: @escaping @MainActor () async -> Void
    ) {
        self.repository = repository
        self.isOffline = isOffline
        self.onUnauthorized = onUnauthorized
    }

    func download(_ item: FileLibraryItem) async {
        guard state != .downloading else { return }
        revision &+= 1
        let expectedRevision = revision
        guard !isOffline() else {
            state = .offline
            return
        }

        state = .downloading
        do {
            let downloaded = try await repository.downloadFile(item)
            guard expectedRevision == revision else {
                try? FileManager.default.removeItem(at: downloaded.localURL)
                return
            }
            state = .ready(downloaded)
        } catch is CancellationError {
            guard expectedRevision == revision else { return }
            state = .idle
        } catch {
            guard expectedRevision == revision else { return }
            await handle(error)
        }
    }

    func cancel() {
        revision &+= 1
        if state == .downloading { state = .idle }
    }

    func discardLocalCopy() {
        revision &+= 1
        if case let .ready(downloaded) = state {
            try? FileManager.default.removeItem(at: downloaded.localURL)
        }
        state = .idle
    }

    private func handle(_ error: Error) async {
        if error.isUnauthorized {
            state = .unauthorized
            await onUnauthorized()
            return
        }
        if case LibreChatProtocolError.httpStatus(403, _, _) = error {
            state = .forbidden
            return
        }
        if case LibreChatProtocolError.httpStatus(let status, _, _) = error,
           status == 404 || status == 405 || status == 501 {
            state = .unavailable
            return
        }
        if error as? FileLibraryError == .unavailable {
            state = .unavailable
            return
        }
        state = .failed(error.userFacingMessage)
    }
}

@MainActor
@Observable
final class FileDeletionModel {
    enum State: Equatable {
        case idle
        case deleting
        case deleted
        case retained(FileLibraryDeletionResult.Attempt)
        case offline
        case forbidden
        case unavailable
        case unauthorized
        case verificationRequired
        case failed(String)
    }

    private let repository: any FileLibraryRepository
    private let isOffline: @MainActor () -> Bool
    private let onUnauthorized: @MainActor () async -> Void
    private var revision: UInt64 = 0

    private(set) var state: State = .idle

    init(
        repository: any FileLibraryRepository,
        isOffline: @escaping @MainActor () -> Bool,
        onUnauthorized: @escaping @MainActor () async -> Void
    ) {
        self.repository = repository
        self.isOffline = isOffline
        self.onUnauthorized = onUnauthorized
    }

    func delete(_ item: FileLibraryItem) async -> FileLibraryDeletionResult? {
        guard state != .deleting else { return nil }
        revision &+= 1
        let expectedRevision = revision
        guard FileLibraryPresentation.canDelete(item) else {
            state = .unavailable
            return nil
        }
        guard !isOffline() else {
            state = .offline
            return nil
        }

        state = .deleting
        do {
            let result = try await repository.deleteFile(item)
            guard expectedRevision == revision else { return nil }
            switch result.disposition {
            case .deleted:
                state = .deleted
                return result
            case .retained:
                state = .retained(result.attempt)
                return nil
            }
        } catch is CancellationError {
            guard expectedRevision == revision else { return nil }
            state = .verificationRequired
            return nil
        } catch {
            guard expectedRevision == revision else { return nil }
            await handle(error)
            return nil
        }
    }

    private func handle(_ error: Error) async {
        if error.isUnauthorized {
            state = .unauthorized
            await onUnauthorized()
            return
        }
        if case LibreChatProtocolError.httpStatus(403, _, _) = error {
            state = .forbidden
            return
        }
        if error as? FileLibraryError == .unavailable {
            state = .unavailable
            return
        }
        if error as? FileLibraryError == .deletionVerificationRequired {
            state = .verificationRequired
            return
        }
        state = .failed(error.userFacingMessage)
    }
}
